### ISSUE TITLE
Very high number of mosaic predictions

### ISSUE THREAD

**Issue by gevro** [shishenyxx/DeepMosaic#25]
Hi,
My input into deepmosaic is mutect2 tumor only mode of 250x WGS healthy human tissue.
After mutect2 I run GATK LearnReadOrientationModel and FilterMutectCalls, and I keep only PASS variants. This leaves 119360 candidate variants

However, I am getting 12350 variants from Deepmosaic = mosaic prediction.

Even after filtering for gnomad = 0, all_repeat = 0 , segdup = 0, homopolymer = 0, dinucleotide = 0, I'm still getting 10,380 variants.

This seems much too high for 250x healthy tissue.

What do you recommend as input into deepmosaic instead of the above, or any other way to filter?

Thanks

**Comment by shishenyxx** [comment]
> Hi, My input into deepmosaic is mutect2 tumor only mode of 250x WGS healthy human tissue. After mutect2 I run GATK LearnReadOrientationModel and FilterMutectCalls, and I keep only PASS variants. This leaves 119360 candidate variants
> 
> However, I am getting 12350 variants from Deepmosaic = mosaic prediction.
> 
> Even after filtering for gnomad = 0, all_repeat = 0 , segdup = 0, homopolymer = 0, dinucleotide = 0, I'm still getting 10,380 variants.
> 
> This seems much too high for 250x healthy tissue.
> 
> What do you recommend as input into deepmosaic instead of the above, or any other way to filter?
> 
> Thanks

Hi gevro,

Thank you for using DeepMosaic! From my own experience, I feel that depending on sample origin and how many samples you took to extract your DNA, it might vary a lot. For clonally expanded samples such as skin, I've seen similar or even higher numbers for ~300x WGS. Even for non-clonally expanded tissues such as the brain, some individuals might exhibit higher clonal mutations at 250x (https://www.science.org/doi/10.1126/science.abm6222 for example). 
Something that I can think of to rule out technical biases:
1. Are they all with very similar allelic fractions (which indicates contaminations)?
2. Are they more enriched in certain chromosomes/genomic regions (which indicate aneuploidy/CNV/SV)?

If they all look normal, to further filter out potential artifacts, I think you can also try some indel annotations (https://github.com/shishenyxx/PASM/tree/master/Snakemake_pipeline) to rule out variants that are close to germline indels. 

BTW, did you use indel realigned and base quality score recalibrated bams as input? GATK4 doesn't require these because HaplotyperCaller and Mutect2 will do the local indel realign internally, but mosaic caller that doesn't have these built-in will require those processes. 

Also if I remember correctly you generated your bam from cram files. Do you know if it is a lossless cram (which is smaller than the original bam but not too much by its nature) that still keeps all the base quality, or a lossy one (which normally is significantly smaller) that only has the same base quality for each genomic position?

Best,

Xiaoxu

**Comment by gevro** [comment]
Thanks for detailed answers!

1. I am originally generating CRAM with standard samtools -C, so it should be lossless.
2. I am planning two kinds of analyses:
 a. Custom mosaic caller that uses indel-realigned + base quality score recalibration BAM. In this situation, should I input to DeepMosaic also the indel-realigned + base quality score recalibration BAM file?
 b. Mutect2 that uses NON-indel realigned and NON base quality score recalibration BAM. In this situation, should I input to DeepMosaic the NON-indel realigned and NON base quality score recalibration BAM?

3. I will look into germline indel filtering.
4. Most of the variants I'm seeing are with upper CI MAF > 0.3. I am thinking of filtering those out because they could be germline. Would that be a good idea?
5. I do not yet see clear enrichment in specific regions.

**Comment by shishenyxx** [comment]
> Thanks for detailed answers!
> 
>     1. I am originally generating CRAM with standard samtools -C, so it should be lossless.
> 
>     2. I am planning two kinds of analyses:
>        a. Custom mosaic caller that uses indel-realigned + base quality score recalibration BAM. In this situation, should I input to DeepMosaic also the indel-realigned + base quality score recalibration BAM file?
>        b. Mutect2 that uses NON-indel realigned and NON base quality score recalibration BAM. In this situation, should I input to DeepMosaic the NON-indel realigned and NON base quality score recalibration BAM?
> 
>     3. I will look into germline indel filtering.
> 
>     4. Most of the variants I'm seeing are with upper CI MAF > 0.3. I am thinking of filtering those out because they could be germline. Would that be a good idea?
> 
>     5. I do not yet see clear enrichment in specific regions.

Thank you, gevro,

2. please input to DeepMosaic inde-aligned + BQSRed bams
4. Are they genomes or exomes? I think you can safely filter out exomes with low depth (higher upper CI) 0.3 or 0.35 might be a OK cutoff but I would plot the distribution of all the variants and see whether there is a peak that seems to be deviated from 0.5.

Please keep me posted and reach out if you have further questions.

Best,

Xiaoxu

**Comment by gevro** [comment]
Thanks!
1. These are genomes. Regardless, I will plot the distribution to see where it might be ok to put a cutoff.

2. Do you have an answer to this question too?
"b. Mutect2 that uses NON-indel realigned and NON base quality score recalibration BAM. In this situation, should I input to DeepMosaic the NON-indel realigned and NON base quality score recalibration BAM?"
 -> In the situation where I just use Mutect2, we do not have a realigned + base quality score recalibrated BAM. So is it ok to input to Deepmosaic the NON realigned / NON base quality score recalibrated BAM that was the input for Mutect2?

**Comment by shishenyxx** [comment]
> Thanks!
> 
>     1. These are genomes. Regardless, I will plot the distribution to see where it might be ok to put a cutoff.
> 
>     2. Do you have an answer to this question too?
>        "b. Mutect2 that uses NON-indel realigned and NON base quality score recalibration BAM. In this situation, should I input to DeepMosaic the NON-indel realigned and NON base quality score recalibration BAM?"
>        -> In the situation where I just use Mutect2, we do not have a realigned + base quality score recalibrated BAM. So is it ok to input to Deepmosaic the NON realigned / NON base quality score recalibrated BAM that was the input for Mutect2?

I don't recommend using un-realigned and un-BQSRed bam. You might find a lot of false positive calls.

**Comment by gevro** [comment]
But doesn't Mutect2 perform this internally? So the VCF that Mutect2 produces should be fine.

Official best practices for Mutect2 does not require prior indel realignment and BQSR.

So if the Mutect2 VCF output is ok, would DeepMosaic know how to handle that non-realigned/non-BQSR BAM file? If not, then I can do prior indel realign+BQSR even though Mutect2 doesn't need it, just so Deepmosaic will have it.

**Comment by shishenyxx** [comment]
Mutect2 has the built-in indel realignment but the base quality is still not recalibrated, this may or may not be an issue depending on the variation of quality, especially for reads carrying mutant alleles.
Because indel realignment and BQSR are not implemented by DeepMosaic when the images are generated the model is still looking at images from non-indel-realigned bam. If you are using other non-GATK callers you might have to do the same process.

Best,

Xiaoxu

**Comment by gevro** [comment]
Sounds good - so I will do indel realignment + BQSR before Mutect2, so that both Mutect2 and DeepMosaic have indel realigned + BQSR bam files.
