### ISSUE TITLE
Too many mutect2 variants

### ISSUE THREAD

**Issue by gevro** [shishenyxx/DeepMosaic#30]
Hi,
For my 250x genome (after BQSR and indel realignment) has 4 million PASS variants.

Is that normal? That seems like too much.

Anything else that you do standard to pre-filter the variants to reduce the number?

Thanks

**Comment by gevro** [comment]
I just saw that I can follow the bsmn pipeline filtering. I will try that.

**Comment by gevro** [comment]
Actually, I would appreciate guidance on this. What is the best level of filtering to give to Deepmosaic?
 1. All haplotypecaller (with appropriate ploidy setting) calls?
 2. Haplotypecaller calls after some of the bsmn best practices filtering?
 3. Haplotypecaller calls after all of the bsmn best practices filtering?

If Option 1 is way too many variants.
If Option 2 - not clear which filters if it should be a subset.
If Option 3 - not clear what the purpose of deepmosaic would be then if we are already doing such heavy filtering, what would the added value of deepmosaic be?

Thanks for guidance!

**Comment by shishenyxx** [comment]
> Actually, I would appreciate guidance on this. What is the best level of filtering to give to Deepmosaic?
> 
>     1. All haplotypecaller (with appropriate ploidy setting) calls?
> 
>     2. Haplotypecaller calls after some of the bsmn best practices filtering?
> 
>     3. Haplotypecaller calls after all of the bsmn best practices filtering?
> 
> 
> If Option 1 is way too many variants. If Option 2 - not clear which filters if it should be a subset. If Option 3 - not clear what the purpose of deepmosaic would be then if we are already doing such heavy filtering, what would the added value of deepmosaic be?
> 
> Thanks for guidance!

Hi gevro,

Thank you for your questions! May I ask what sample you use for your Mutect2 as the panel of normal (just to rule out systematic bias, you can even download data sequenced in a similar sequencer with similar depth)? Are they also 250x or they are sequenced with lower depth? 

For Mutect2 single mode I have the ["Leave One Out"](https://github.com/shishenyxx/Sperm_control_cohort_mosaicism/tree/master/Pipelines/Mosaic_Calls/Mutect2_single_mode/leave_one_out) version, as well as a ["Full Panel of Normal"](https://github.com/shishenyxx/Adult_brain_somatic_mosaicism/tree/master/pipelines/WGS_SNV_indel_calling_pipeline/Mutect2_single_mode) version that I was using, leave one out mode might be easier, assuming mosaic variants you want are private. With 250x I can get several thousands of PASS variants that I use for DeepMosaic (Also for MosaicForecast if you want).

On the other hand, the HaplotypeCaller polidy 50 calls following BSMN pipelines might be too strict if you aim at variant discovery (but OK if you want to do lineage tracing because the validation rate is better). You can try to filter based on population frequency, near indel, homopolymer, repeats, etc. But ignore the more sample-specific filters from BSMN pipeline and see how many variants you can get.

Hope that helps you,

Xiaoxu

**Comment by gevro** [comment]
Hi,
My samples are 250x PCR-free on Novaseq 6000.

I am using GATK ploidy 50, and then this PON from BSMN: PON.q20q20.05.5.biallelic.vcf.gz. I am also now adding some filters for regions that tend to have false positives (seg dups, CNVs).

I prefer higher specificity than sensitivity.

Would this approach work? Or would you suggest the Mutect2 approach. If Mutect2, could I also still use the above BSMN 1kg PON?

**Comment by shishenyxx** [comment]
> Hi, My samples are 250x PCR-free on Novaseq 6000.
> 
> I am using GATK ploidy 50, and then this PON from BSMN: PON.q20q20.05.5.biallelic.vcf.gz. I am also now adding some filters for regions that tend to have false positives (seg dups, CNVs).
> 
> I prefer higher specificity than sensitivity.
> 
> Would this approach work? Or would you suggest the Mutect2 approach. If Mutect2, could I also still use the above BSMN 1kg PON?

Hi gevro,

I think this should already work, filtering out gnomAD 0.01 or 0.005 might also help reduce the input number and they tend to be false positives or contaminations (DeepMosaic can do it but you have to throw everything in). You can try Mutect2 if the number is still very high. I also want to point out that the BSMN PON are brain samples so if you are using tissues other than the Brain maybe using the 'leave one out' strategy is better.

Best,

Xiaoxu

**Comment by gevro** [comment]
Thank you so much for the advice! Last question - do you suggest we filter prior to DeepMosaic the variants with non-PASS VQSR tranches? i.e. FILTER = VQSRTrancheINDEL99.00to99.90, etc.

Or should we keep variants labeled with these lower-quality VQSR tranches?

**Comment by shishenyxx** [comment]
> Thank you so much for the advice! Last question - do you suggest we filter prior to DeepMosaic the variants with non-PASS VQSR tranches? i.e. FILTER = VQSRTrancheINDEL99.00to99.90, etc.
> 
> Or should we keep variants labeled with these lower-quality VQSR tranches?

Hi gevro,

For higher specificity filtering for quality definitely will help, but first plot the quality distribution to exclude batch/sample variations (you might need individualized cutoff for VQSR scores).

Best,

Xiaoxu

**Comment by gevro** [comment]
Thanks as always!

**Comment by gevro** [comment]
Though I would add - I worry that mosaic variants would be exactly in those lower level VQSR tranches and simply removing lower VQSR score variants would miss a lot of mosaic variants. So I might try to keep them and then let DeepMosaic figure out what is likely true calls.

**Comment by shishenyxx** [comment]
> Though I would add - I worry that mosaic variants would be exactly in those lower level VQSR tranches and simply removing lower VQSR score variants would miss a lot of mosaic variants. So I might try to keep them and then let DeepMosaic figure out what is likely true calls.

Hi gevro,

That's why I suggested adaptive filtering -- you can choose top 5% or 10% quality for each sample. This way you are not simply using a hard cutoff. But I agree reads with variants will have slightly lower mapping quality and thus lower overall quality. You can input them to DeepMosaic as long as the numbers are not too much (I think several dozens of thousand is still manageable).

Best,

Xiaoxu
